version: '3.9'

services:
  web:
    container_name: currencies
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/currencies
      - ./app/db.sqlite3:/currencies/app/db.sqlite3
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A currencies worker -l info
    volumes:
      - .:/currencies
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A core beat -l info
    volumes:
      - .:/currencies
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:5000"
    volumes:
      - ./nginx/appseed-app.conf:/etc/nginx/conf.d/appseed-app.conf:ro
      - .:/currencies
    depends_on:
      - web