version: '3.9'

services:
  web:
    container_name: currencies
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/currencies
      - ./db.sqlite3:/currencies/db.sqlite3
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
  celery:
    container_name: celery
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/currencies
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
    command: celery -A currencies worker --beat --scheduler django --loglevel=INFO

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "5085:5085"
    volumes:
      - ./nginx/appseed-app.conf:/etc/nginx/conf.d/appseed-app.conf:ro
    depends_on:
      - web