# Generated by Django 4.2.10 on 2024-02-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charcode', models.CharField(max_length=3, unique=True, verbose_name='Код валюты')),
                ('date', models.DateField(verbose_name='Дата')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=7, verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
            },
        ),
    ]
